#-Information---------------------------------------------------------------------------------------
name: cge_pointfinder_kma
version: 1.0.6
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  category: resistance
  schema_version: 2.0
  target: sample
  type: pipeline
  recommendation: recommended
  description: >
    Finds chromosomal point mutations with the CGE pointfinder tool
#---------------------------------------------------------------------------------------------------

#-Docker location-----------------------------------------------------------------------------------
dockerfile: &dockerfile "docker://stefanocardinale/cge_pointfinder_kma:1.0.6"
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
  species_mapping:
    "Campylobacter jejuni": [campylobacter]
    "Escherichia coli": [escherichia_coli]
    "Salmonella enterica": [salmonella]
    "Enterococcus faecalis": [enterococcus_faecalis]
    "Enterococcus faecium": [enterococcus_faecium]
    "Helicobacter pylori": [helicobacter_pylori]
    "Klebsiella pneumoniae": [klebsiella]
    "Klebsiella oxytoca": [klebsiella]
    "Klebsiella aerogenes": [klebsiella]
    "Mycobacterium tuberculosis": [mycobacterium_tuberculosis]
    "Neisseria gonorrhoeae": [neisseria_gonorrhoeae]
    "Plasmodium falciparum": [plasmodium_falciparum]
    "Staphylococcus aureus": [staphylococcus_aureus]
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  database_path: "bifrost/cge_pointfinder_kma/pointfinder_db"
  adapters_fasta: "/bifrost_resources/adapters.fasta"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    properties:
      paired_reads:
        summary:
          data:
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files:
   - "cge_pointfinder_kma/resistance/filtered_kma_results.tsv"
  sample:
    properties:
      resistance:
        summary:  # see sample_component summary
        component:
          _id: 
          date:  # ObjectId
    report:
      resistance:
  sample_component:
    summary:
    results:
      cge_pointfinder_kma/resistance/filtered_kma_results.tsv: {}
#---------------------------------------------------------------------------------------------------